requirements:

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Hostname"
        unit_of_measurement: ""
        icon: "mdi:form-textbox"