requirements:

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "Message time"
        unit_of_measurement: ""
        icon: "mdi:clock"