requirements:

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "*"
      payload:
        name: "File content"
        unit_of_measurement: ""
        icon: "mdi:file"